CITIES = [
  "Sxwōxwiyám: Sqáyéx/Xwyélés",
  "Ceuta",
  "Juanhaven",
  "佳市",
  "East Sarah",
  "山武郡横芝光町",
  "川崎市宮前区",
  "Blondel-sur-Pottier",
  "West Christine",
  "Lake Amandahaven",
  "Weekshaven",
  "Breuerscheid",
  "Matisscheid",
  "Groß Naemidorf",
  "Groß Maxim",
  "Scharfgrün",
  "Neu Liahhagen",
  "Eliasstadt",
  "Mögenburgscheid",
  "Edirne",
  "Eskişehir",
  "İzmir",
  "İstanbul",
  "Van",
  "Şırnak"
].map { |s| s.encode("UTF-8") }
