SITE_TYPES = [
  "Other Practices: Canoe Races",
  "Other Practices: Canoe training",
  "Other Practices: Healing Place",
  "Sxwōxwiyám: Other",
  "Sxwōxwiyám: Sqáyéx/Xwyélés",
  "Sxwōxwiyám: Tel Sweyal",
  "Sxwōxwiyám: Wōqw'",
  "Sxwōxwiyám: X̠éyt",
  "Xá:Xa: Burial",
  "Xá:Xa: Cave",
  "Xá:Xa: Mimestíyexw Place",
  "Xá:Xa: Regalia Placement Place",
  "Xá:Xa: Shxwexwó:s Cave",
  "Xá:Xa: Stl’áleqem Place",
  "Xá:Xa: Sxwó:yxwey Origin Place",
  "Xá:Xa: S’ó:lmexw Place",
  "Xá:Xa: Tunnel",
  "Metaphysical Being: Pítxel",
  "Metaphysical Being: Shxwexwos",
  "Metaphysical Being: Spirit Animal",
  "Metaphysical Being: Sásq’ets",
  "Spiritual Practice: Power Questing",
  "Spiritual Practice: Afterbirth Place",
  "Spiritual Practice: Burning Place",
  "Spiritual Practice: Ceremonial Feeding",
  "Spiritual Practice: Healing Rock",
  "Spiritual Practice: Isolation/Puberty Place",
  "Spiritual Practice: Prayer Tree",
  "Spiritual Practice: Smílha Place",
  "Spiritual Practice: Sweats Place",
  "Spiritual Practice: Sxwó:yxwey Place",
  "Material Culture: Archaeological Site",
  "Material Culture: Archaeological Site Lead",
  "Material Culture: CMT",
  "Material Culture: Surficial Find",
  "Material Culture: Symbol",
  "Navigation: Geographic Location",
  "Resource Management: Burning Place",
  "Resource Management: Clam Bed",
  "Resource Management: Deer Drive",
  "Resource Management: Fishingweir/Trap",
  "Resource Management: Irrigation/Spring/Waterway",
  "Resource Management: Plantation/Farm",
  "Resource Management: Spawning Ground",
  "Resource Harvesting: Aquatic Harvesting",
  "Resource Harvesting: Aquatic Processing",
  "Resource Harvesting: Habitation",
  "Resource Harvesting: Hunting",
  "Resource Harvesting: Terrestrial Harvesting",
  "Resource Harvesting: Trapping",
  "Resource Harvesting: Travel"
].map { |s| s.encode("UTF-8")}
